services:
  - type: web
    name: smartcrs
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python manage.py migrate --noinput && gunicorn complaintsystem.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SERVE_MEDIA_FILES
        value: "True"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: ADMIN_REGISTRATION_KEY
        sync: false
      - key: STAFF_REGISTRATION_KEY
        sync: false
